### ISSUE TITLE
Consider inserting "Upload Repo" at position 0 or 1

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan-package-tools#110]
It looks like package tools inserts "REMOTES" at position 0, but upload repo is inserted last by default for us.  Would anyone object to inserting it at position 0 or 1?

**Comment by uilianries** [comment]
You can force the order if you include the upload repo in remote list: [packager.py](https://github.com/conan-io/conan-package-tools/blob/develop/conan/packager.py#L192)

or call a `conan remote update <upload_repo> --insert` (maybe using Conan API)

But, if you change the current default order, you can and will break some builds.

In my case, for example, if I need some specific package already built, I push to my bintray repo, but when I need a standard configuration, as x86_64 I pull from conan-center. So, If you change such order, my build will try to pull all my packages from my bintray repo and I don't have all configurations built in there. As result, my build won't work, because I don't use *missing* option.

**Comment by solvingj** [comment]
Good to know, exactly the type of thing we would want to avoid breaking.  We could do a workaround of adding the repo as both a remote and as the upload repo.  That's probably the solution since we're probably the only group for whom this is significantly impactful.
