### ISSUE TITLE
Broken mingw builds on appveyor

### ISSUE THREAD

**Issue by rockdreamer** [conan-io/conan-package-tools#126]
Hi, I'm trying to build my header only library that consumes the [lasote/gtest](https://github.com/lasote/conan-gtest) googletest package from  on appveyor with mingw.
I read the documentation of conan-package-tools and tried to follow the lead of the conan-zlib project.
I added the MINGW_CONFIGURATIONS: "5.4@x86_64@seh@posix" line to appveyor.yml and, since the package isn't available, call "python build.py --build missing" in the test_script.
To my surprise, the [build log](https://ci.appveyor.com/project/rockdreamer/throwing-ptr/build/job/fvm5wllnek2iagen) says that the compiler C:/MinGW/bin/gcc.exe is not able to compile a simple test program.

Is cmake picking up the right compiler?
If not, is there an error in my scripts?

Thanks.

**Comment by memsharded** [comment]
Thanks for reporting. An initial check, an everything seems fine on your side, might be conan-package-tools, or something that has changed in appveyor. Investigating.

**Comment by memsharded** [comment]
I think your issue could be related to what I have reported in https://github.com/conan-io/conan/issues/2134

The mingw that is automatically being defined in the created profile, does **not** apply automatically to the build of  the gtest library with that gcc 5.4 compiler.

Right now I am trying locally, and it failed because my local mingw gcc is 4.9, so fortunately conan detected and throwed an error. So I am trying to working around it by first building gtest with this 5.4 config ( I have put in a profile):

```bash
$ conan install gtest/1.8.0@lasote/stable -pr=gcc54 --build=missing
```
With my gcc54 profile:
```text
[settings]
compiler=gcc
os=Windows
compiler.version=5.4
compiler.libcxx=libstdc++
compiler.exception=seh
compiler.threads=posix
arch=x86_64
build_type=Release

[build_requires]
mingw_installer/1.0@conan/stable
```

The bad news is that gtest doesn't build with this compiler, should be checked why.

**Comment by rockdreamer** [comment]
Thanks for following this, I've since moved on to catch for running tests. It's sad that the current version doesn't work with VS2013 but I'm happy to stick with a previous one. This was made a lot easier thanks to conan! :)
