### ISSUE TITLE
Docker builds affect host conan.conf and default profile

### ISSUE THREAD

**Issue by leugenea** [conan-io/conan-package-tools#165]
It's very strange behaviour for me: I run docker builds to isolate build environment from host, but instead build modifies host settings.
Looks like problem is in `DockerTestPackageRunner.run` method:
```
command = "%s docker run --rm -v %s:/home/conan/project -v " \
          "%s:/home/conan/.conan %s %s /bin/sh -c \"" \
          "rm -f /home/conan/.conan/conan.conf && cd project && " \
          "rm -f /home/conan/.conan/profiles/default && " \
          "(conan profile new default --detect || true) && " \
          "run_create_in_docker\"" % (self.sudo_command, os.getcwd(), self.conan_home,
                                      env_vars, self.docker_image)
```

Why not mount only `os.path.join(self.conan_home, 'data')` and remove `conan.conf` and default profile?

**Comment by lasote** [comment]
Well, the registry of the remotes is also shared. I think the historical reason to share data with the host (upload packages altogether) has not much sense since we split the build in CI in different builds. So, probably the way to fix this is to not sharing at all with the host and passing all the needed config to docker.

**Comment by solvingj** [comment]
Just started to realize the implications of the sharing with the local profile myself.  Agree it's not good. Vote for passing all configs to container via `-e ENV_VAR=Value` rather than the JSON serialization because of all the JSON escaping in the logs.  I think we could make a serialize/deserialize based on environment variables, doing `        for var, value in os.environ.items():`

**Comment by lasote** [comment]
The `0.17.0.beta1` doesn't share data with the container (except the project folder) so it should be fixed now. 

Please try it and report. `pip install conan-package-tools==0.17.0b1`

**Comment by leugenea** [comment]
That really works cool, thanks!
