### ISSUE TITLE
Change conan_runner temp container name to be unique

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan-package-tools#196]
The current name of `conan_runner` will cause contention when running multiple docker builds in parallel on a build machine.  Need to make it unique.

**Comment by lasote** [comment]
But the issue will still persist because the ``conan_runner`` name is just a temporary name to commit to the base image, so the base image will be tried to be overwritten while running builds, probably it will fail. I think the best choice is to use ``always_update_conan_in_docker=True`` and avoid the image commiting.

**Comment by solvingj** [comment]
@SSE4 I see your point.  Anything that affects the host OS environment at all is effectively incompatible with CI systems which don't start with completely independent OS.

**Comment by uilianries** [comment]
Closing this one since it is invalid.
