### ISSUE TITLE
tools.vcvars_command empty when running with package tools

### ISSUE THREAD

**Issue by osechet** [conan-io/conan-package-tools#35]
My package build fails in appveyor because `tools.vcvars_command()` returns an empty string. I found the problem occurs when the build is started with the `build.py` script. On my machine, if I build the package normally (with `test_package` for example), everything is fine. If I call `python build.py`, the build fails with the same error as in appveyor:
```
&& was unexpected at this time.
```

A failing build is accessible here: https://ci.appveyor.com/project/osechet/conan-qt-base/build/job/mvkk4vc67rfsarow

**Comment by memsharded** [comment]
Maybe it is not an issue with conan-package-tools. I recently changed the behavior of ``tools.vcvars_command()`` because it was a bit weird and problematic. So the current implementation is:

- It checks if the vcvars are already set, if they don't match the current conan settings, it will raise an error (this was silently ommitted before).
- If the vcvars are already set, and they match the current conan settings, return an empty string, to avoid calling it twice
- If the vcvars are not set, it returns an string with the command to set them.

So, conanfiles that want to concat the command must basically do:

```python
vcvars = tools.vcvars_command()
vcvars = vcvars + " && " if vcvars else ""
```

Sorry if it broke your build, I am trying to imagine some behavior that would be backwards compatible, but I am not aware of it. Any suggestion or ideas?

**Comment by osechet** [comment]
Ok I followed your suggestion and it fixed the issue. But I don't have any idea how to do your modification without breaking anything. 
Thanks.

**Comment by memsharded** [comment]
Yes, that was the problem. Glad that it fixed it. I think we can close this issue, thanks for reporting!
