### ISSUE TITLE
Windows builds end to C:\

### ISSUE THREAD

**Issue by madduci** [conan-io/conan-package-tools#41]
Hi

I'm using conan-package-tools in Windows and when I run the `python build.py` command, all the packages are built in C:\.conan folder instead of C:\Users\user\.conan.
There's an interesting effect too: in C:\Users\user\.conan\MyPackage\ there are .conan_link files pointing to the C:\.conan folder.

How can I force to build the packages in user folders instead of on C: root folder?

**Comment by memsharded** [comment]
Hi @madduci 

This is a side issue of the Windows path length limitation. There is a flag in packages that defines an alternative behavior: http://docs.conan.io/en/latest/reference/conanfile.html#short-paths

The behavior of this path shortener is:
- Take the location of your local conan storage, typically C:/User/name/.conan
- Take the drive C:
- Use a shorter path C:/.conan/short_path/...

All the that are marked to be shortened in the local conan storage implements a "portable symlink" implemented with that .conan_link file. Yes, the behavior of symlinks in Win was problematic, so we finally workarounded it with a file.

You could remove the ``short_paths=True`` from recipes, but if you are using packages with long paths (Boost, Qt, and others), they will most likely fail in Windows due to that limitation.

**Comment by madduci** [comment]
Ok thanks for the clarification
